version: '3'

services:
  accrual-api:
    build:
      context: .
      dockerfile: accrual.dockerfile
    restart: on-failure
    ports:
      - '8082:8082'
    working_dir: "$PWD"
    environment:
      RUN_ADDRESS: 'accrual-api:8082'
    networks:
      - app-network
    volumes:
      - "$PWD:$PWD"

  gophermart-api:
    build:
      context: .
      dockerfile: gophermart.dockerfile
    command: tail -f /dev/null
    restart: on-failure
    ports:
      - '8081:8081'
    working_dir: "$PWD"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      RUN_ADDRESS: 'gophermart-api:8081'
      DATABASE_URI: 'postgres://usr:psswrd@postgres:5432/gophermart?sslmode=disable'
      ACCRUAL_SYSTEM_ADDRESS: 'accrual-api:8082'
      SECRET_KEY: 'gljfsj;312sf;kdhrf;'
      LOG_LEVEL: 'debug'
    networks:
      - app-network
    volumes:
      - "$PWD:$PWD"

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
      - "54323:5432"
    environment:
      POSTGRES_USER: 'usr'
      POSTGRES_PASSWORD: 'psswrd'
      POSTGRES_DB: 'gophermart'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
